### ISSUE TITLE
Service update from the app

### ISSUE THREAD

**Issue by edotassi** [edotassi/AmazMod#223] opened 2018-09-24 12:10 UTC
- [x] detect new update
- [x] download service-release-xxx.apk
- [x] upload to watch
- [x] install
- [ ] reboot watch

**Comment by rpodgorny** [comment] 2018-10-04 10:33
isn't this a duplicate of https://github.com/edotassi/AmazMod/issues/153 ?

**Comment by lfom** [comment] 2018-10-22 13:48
Removing and re-adding admin owner isn't needed actually, only if you must uninstall the app, updating it doesn't require these.

**Comment by lfom** [comment] 2018-11-11 08:31
Last one was replaced with "restart launcher", with no known side-effects so far (0680a8bac07d7b358d27e6aa93688c5f9ce7c5e9). Closing.

**Closed by lfom** 2018-11-11 08:31 UTC
Labels: enhancement
