### ISSUE TITLE
Significantly increase in battery usage? 

### ISSUE THREAD

**Issue by daenny** [edotassi/AmazMod#165] opened 2018-08-27 21:03 UTC
After the latest update my battery runtime dropped significantly. Previously it was roughly 4days. Now it's just about 1 day. You can see the slope difference in the chart. I already rebooted multiple times... Anybody else with this issudt? 
![screenshot_amazmod_20180827-225453](https://user-images.githubusercontent.com/3392004/44686054-54fef980-aa4d-11e8-85f0-d37428632f92.png)

**Comment by lfom** [comment] 2018-08-28 02:33
Do you have any other APKs installed on watch?

**Comment by daenny** [comment] 2018-08-28 06:15
Yes a taskmanager and a filemanager, but they were already installed before the update. You can see when I installed the update I charged to 100 procent. 
![screenshot_amazmod_20180828-081409](https://user-images.githubusercontent.com/3392004/44704107-720de980-aa9a-11e8-87ff-be66a13ec3e7.png)

**Comment by EgorOA** [comment] 2018-08-28 08:34
My experience: before service installation - 6 days, after - 5 days. So there is a noticeable difference.

**Comment by edotassi** [comment] 2018-08-28 08:41
@EgorOA do you use custom ui for notifications?

**Comment by EgorOA** [comment] 2018-08-28 08:45
Surely, I'm using AmazMod service to get notifications.

**Comment by edotassi** [comment] 2018-08-28 08:58
@EgorOA custom ui notifications consume more battery because they wake up cpu.

**Comment by lfom** [comment] 2018-08-28 16:49
@edotassi yes, but the drain @daenny is having is something different, it's a continuous drain. I saw in logcat that something is blocking the watch to go into deep sleep mode (system cannot write to /sys/power/mode or something like that), but I didn't find the cause yet...

**Comment by daenny** [comment] 2018-08-28 21:02
I use the custom UI, and also "standard style" notifications enabled. I also have "turn screen on with notification" enabled.

**Comment by daenny** [comment] 2018-08-30 18:17
![screenshot_amazmod_20180830-201257](https://user-images.githubusercontent.com/3392004/44870768-4ef95a80-ac91-11e8-88c7-0cff5143b987.png)
Yesterday I enabled "Disable screen on" and the battery life seems better again. So maybe that is where it is hanging? Btw I find the settings very confusing. The statement should always be "enable Xxx" and then the toggle shows if it is disabled or not.

**Comment by lfom** [comment] 2018-08-30 18:58
These long continuous drop in battery charge should not happen either way, something is wrong. I have factory reset my watch and with only AmazMod installed (no other APKs on watch) it looks fine so far. If I don't get anything weird after 4 days, I will activate other options and continue to test...

**Comment by lfom** [comment] 2018-09-22 05:56
It seems it might be due to a firmware bug, I haven't experienced this since a long ago. So closing it as of 1.0.49 release.

**Closed by lfom** 2018-09-22 05:56 UTC
Labels: evaluating
